import { Inter } from 'next/font/google';
import './css/globals.css';
import Providers from './Components/providers';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Flight Test Weather Dashboard',
  description: 'Generated by Jay Lee',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
